In [1]:
import pandas as pd
import numpy as np

### hash table

In [28]:
val = np.random.rand(5)
val

array([0.16662146, 0.1319328 , 0.82117287, 0.53670879, 0.95469871])

In [32]:
key=[]
[key.append(str(val[i])[-3:]) for i, element in enumerate(val)]
print(key) 

['907', '289', '744', '351', '091']


In [39]:
htable={}
for i, element in enumerate(val):
    htable[key[i]] = element
print(htable)

{'907': 0.16662146245585907, '289': 0.131932803466289, '744': 0.821172871333744, '351': 0.5367087895812351, '091': 0.9546987136906091}


In [104]:
# this takes a bunch of values and puts them into a Hash Table
class Hash:
    def __init__(self, values):
        self.val = values    
        self.keys = self.get_keys()
        self.table = self.make_table()
    
    #method: get all keys using hash function
    def get_keys(self):
        keys=[]
        [keys.append( self.hash_function(element) ) for i, element in enumerate(self.val)]
        return keys

    #method: map from the universe of keys to the keys for my values
    def hash_function(self, value):
        return str(value)[-3:]
        
    #method: create a hash table from the keys and values
    def make_table(self):
        htable={}
        for i, element in enumerate(self.val):
            htable[self.keys[i]] = element
        return htable
    
    #method: insert
    def insert(self, new_val):
        self.keys.append( self.hash_function(new_val) )
        self.table[ self.hash_function(new_val) ] = new_val  
        
# Q: how should I do these without python's shortcuts?
    #method: delete
    def delete(self, key):
        if key in self.keys:
            del self.table[key]
    
    #method: search to find the value for a given key
    def search(self, key):
        if key in self.keys:
            return self.table.get(key)   

In [105]:
my_hash = Hash(val)
#my_hash.keys
#my_hash.table
#my_hash.search('907')
my_hash.delete('907')
#add a value
#my_hash.insert(np.random.rand(1)[0])
#print(my_hash.table)

In [106]:
print(my_hash.table)

{'289': 0.131932803466289, '744': 0.821172871333744, '351': 0.5367087895812351, '091': 0.9546987136906091}


### stack

In [174]:
# this uses an empty list, and performs almost all methods without using list methods 
class Stack:
    def __init__(self):
        self.items = []    
        ## NOTE: Define max size 
        self.top = len(self.items)
    
    #method: push something to the top of the stack
    def push(self, new_item):
        if self.top == len(self.items):
            self.items.append(new_item)
        elif self.top < len(self.items):
            self.items[self.top] = new_item
        self.top = self.top + 1
        
    #method: push something to the top of the stack
    def pop(self):
        if self.top == 0:
            return "underflow"
        else:
            pop_value = self.items[self.top-1]
            self.items = self.items[:-1]
            return pop_value 
        #return self.items.pop()
    
    #peek: look at the top without popping it 
    
    #method: populate from values or items
    def populate(self, values):
        #NOTE: MAKE THIS CALL PUSH!!!
        [self.items.append(values[i]) for i,value in enumerate(values)]
        self.top = len(self.items)

In [175]:
s = np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [176]:
my_stack = Stack()
my_stack.populate(s)
my_stack.push(42)
my_stack.pop()
my_stack.push(20)
my_stack.items
#my_stack.top
#my_stack.push(14)
#my_stack.pop()
#my_stack.val

42

### queue

In [194]:
# queues are like a list of customers. First in, first out... follow the queue
# this uses an empty list, and performs almost all methods without using list methods 
class Queue:
    def __init__(self):
        self.items = []    
        self.tail = len(self.items)
        self.head = 0
        
    #method: enqueue something to back of the line
    def enqueue(self, new_item):
        self.items.append(new_item)
        self.tail = self.tail + 1
                
    #method: dequeue something from the front of the line
    def dequeue(self):
        if self.tail == 0:
            return "underflow"
        else:
            # change to self.items = self.items[1:] to keep only the rest
            upfront = self.items[self.head]
            self.head = self.head + 1
            return upfront 
    
    #method: populate from values or items
    def populate(self, values):
        [self.items.append(values[i]) for i,value in enumerate(values)]
        self.tail = len(self.items)

    #method: pull the whole thing
    def get_queue(self):
        return self.items[self.head:self.tail]

In [197]:
my_q = Queue()
my_q.populate(s)
my_q.enqueue(14)
#my_q.items
my_q.dequeue()
my_q.dequeue()
my_q.enqueue(9)
my_q.get_queue()

[2, 3, 4, 5, 6, 7, 8, 9, 14, 9]

### deque

### linked list

In [191]:
class Node: 
    def __init__(self, val): 
        self.val = val 
        self.next = None
        
    #this traverses from a starting point
    def traverse(self):
        while self != None:
            print(self.val)
            self=self.next

    #this searches for x
    def search(self, x):
        count = 1
        while self.val != x and self.next!=None:
            self=self.next
            count +=1
        if self.val == x:
            print(self.val, ' found in node', count)
        if self.next == None:
            print('Value not found.')
            
    #this inserts the value x into the kth spot where spots are indexed by 1
    def insert(self, x, k):
        newnode = Node(x)
        if k == 1:
            newnode.next = self
            newnode.traverse()
        else: 
            count = 2 
            current = self
            while count < k:
                current=current.next
                count+=1
            newnode = Node(x)
            # have the new node point to the rest of the list
            newnode.next = current.next
            # point the current node to the new node
            current.next = newnode
            node1.traverse()
    
    # reverse the list
    def reverse(self):
        prior_node = None 
        while self.next != None:
            hold_next = self.next
            self.next = prior_node
            prior_node = self
            self = hold_next
        self.next = prior_node
        self.traverse()

In [192]:
node1 = Node(3)
node2 = Node(5)
node3 = Node(8)
node1.next = node2
node2.next = node3
#node1.traverse()
#node1.search(10)
node1.insert(4,2)

3
4
5
8


In [193]:
node1.reverse()

8
5
4
3


### heap

In [270]:
def max_heapify(A, heap_size, i):
    left = 2 * i + 1
    right = 2 * i + 2
    largest = i
    if left < heap_size and A[left] > A[largest]:
        largest = left
    if right < heap_size and A[right] > A[largest]:
        largest = right
    if largest != i:
        A[i], A[largest] = A[largest], A[i]
        if i!=0 and i % 2 == 0:
            start = int(i/2 - 1)
            max_heapify(A, heap_size, start)
        elif i!=0 and i % 2 > 0:
            start = int(i/2 - .5)
            max_heapify(A, heap_size, start)
        elif i == 0:
            max_heapify(A, heap_size, i)

class Heap:
    def __init__(self, array):
        self.root = None
        self.size = len(array)
        self.array = array

    def build_max_heap(self):
        heap_size = self.size
        for i in range(heap_size):    
            max_heapify(self.array,heap_size, i)
        return self.array
    
    def extract_max(self):
        self.build_max_heap()
        return self.array[0]
    
    def insert_max(self, val):
        self.array = np.append(val, self.array)
        self.build_max_heap()
        print(self.array)

In [273]:
test = np.array([1,19,36,6,3,25,1,2,7,800])
heap = Heap(test)
heap.build_max_heap()
#heap.extract_max()
heap.insert_max(100)

[800 100  36  25   7  19   1   1   2   6   3]
